# Generated by Django 3.2 on 2022-05-13 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cultivation', '0001_initial'),
        ('greatadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='vaccineinfo',
            name='vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.vaccine'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='turninfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='quarantineinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='fodderinfo',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivation.fodder'),
        ),
        migrations.AddField(
            model_name='fodderinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='fodder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='envronmentinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='cultivationinfo',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greatadmin.animal'),
        ),
        migrations.AddField(
            model_name='cultivationinfo',
            name='clean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivation.clean'),
        ),
        migrations.AddField(
            model_name='cultivationinfo',
            name='fiid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivation.fodderinfo'),
        ),
        migrations.AddField(
            model_name='cultivationinfo',
            name='qiid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivation.quarantineinfo'),
        ),
        migrations.AddField(
            model_name='cultivationinfo',
            name='temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivation.temp'),
        ),
        migrations.AddField(
            model_name='cultivationinfo',
            name='tiid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivation.turninfo'),
        ),
        migrations.AddField(
            model_name='cultivationinfo',
            name='viid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cultivation.vaccineinfo'),
        ),
    ]
