# Generated by Django 3.2 on 2022-05-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greatadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slaughter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('patch', models.CharField(max_length=20, verbose_name='身体部位')),
            ],
            options={
                'verbose_name_plural': '屠宰',
                'db_table': 'pro_slaughter',
            },
        ),
        migrations.CreateModel(
            name='SlaughterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('safe', models.BooleanField(verbose_name='检疫情况')),
                ('is_in', models.BooleanField(default=False, verbose_name='是否入库')),
                ('license', models.DecimalField(decimal_places=0, max_digits=22, verbose_name='屠宰场编号号')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greatadmin.animal')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slaughter.slaughter')),
            ],
            options={
                'verbose_name_plural': '屠宰信息',
                'db_table': 'pro_slaughter_info',
            },
        ),
    ]
