# Generated by Django 3.2 on 2022-05-13 13:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greatadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='文章类别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标识')),
            ],
            options={
                'verbose_name_plural': '文章类型表',
                'db_table': 'home_category',
            },
        ),
        migrations.CreateModel(
            name='HNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('author_name', models.CharField(max_length=100, verbose_name='作者名字')),
                ('gcontent', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容')),
                ('image', models.FileField(blank=True, upload_to='article_image', verbose_name='展示图')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('source_link', models.CharField(blank=True, max_length=200, verbose_name='原文连接')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标识')),
            ],
            options={
                'verbose_name_plural': '文章表',
                'db_table': 'home_news',
            },
        ),
        migrations.CreateModel(
            name='TBCode',
            fields=[
                ('code', models.DecimalField(decimal_places=0, max_digits=65, primary_key=True, serialize=False, verbose_name='序号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greatadmin.animal', verbose_name='动物id')),
            ],
            options={
                'verbose_name_plural': '溯源统计表表',
                'db_table': 'home_TBCode',
            },
        ),
    ]
