# Generated by Django 3.2 on 2022-05-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('homeindex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcode',
            name='listinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.listinfo', verbose_name='清单id'),
        ),
        migrations.AddField(
            model_name='hnews',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeindex.hcategory', verbose_name='文章内容'),
        ),
    ]
