# Generated by Django 3.2 on 2022-05-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标识')),
                ('id', models.DecimalField(decimal_places=0, max_digits=22, primary_key=True, serialize=False, verbose_name='序号')),
                ('address', models.CharField(max_length=40, verbose_name='出生地点')),
                ('aclass', models.CharField(max_length=10, verbose_name='品种')),
                ('fa_mo', models.CharField(max_length=100, verbose_name='父类')),
                ('num', models.IntegerField(default=10, verbose_name='圈栏号')),
                ('dead', models.BooleanField(default=False, verbose_name='是否病死')),
                ('is_sl', models.BooleanField(default=False, verbose_name='是否宰杀')),
                ('is_turn', models.BooleanField(default=False, verbose_name='是否转出')),
                ('license', models.DecimalField(decimal_places=0, max_digits=22, verbose_name='执照号')),
            ],
            options={
                'verbose_name_plural': '动物信息表',
                'db_table': 'pro_animal',
            },
        ),
    ]
