# Generated by Django 3.2 on 2022-05-13 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('greatadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='clgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='养殖企业', to=settings.AUTH_USER_MODEL, verbose_name='养殖企业'),
        ),
        migrations.AddField(
            model_name='animal',
            name='shgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='销售企业', to=settings.AUTH_USER_MODEL, verbose_name='销售企业'),
        ),
        migrations.AddField(
            model_name='animal',
            name='slgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='屠宰企业', to=settings.AUTH_USER_MODEL, verbose_name='屠宰企业'),
        ),
    ]
