# Generated by Django 3.2 on 2022-05-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('heavy', models.IntegerField(verbose_name='销售肉块重量')),
                ('day', models.IntegerField(verbose_name='保质期')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='出售价格')),
            ],
            options={
                'verbose_name_plural': '销售清单信息表',
                'db_table': 'pro_list_info',
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('passage', models.TextField(max_length=400, verbose_name='商品简介')),
            ],
            options={
                'verbose_name_plural': '备忘录信息表',
                'db_table': 'pro_passage',
            },
        ),
        migrations.CreateModel(
            name='SaleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('lisence', models.CharField(max_length=20, verbose_name='销售许可证')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='单价')),
            ],
            options={
                'verbose_name_plural': '销售信息表',
                'db_table': 'pro_sale_info',
            },
        ),
    ]
