# Generated by Django 3.2 on 2022-05-13 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
        ('slaughter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinfo',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='saleinfo',
            name='siid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='slaughter.slaughterinfo'),
        ),
        migrations.AddField(
            model_name='passage',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AddField(
            model_name='listinfo',
            name='saiid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.saleinfo'),
        ),
        migrations.AddField(
            model_name='listinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
    ]
